export const LISTEN_TO_CURRENT_USER_PROFILE = 'LISTEN_TO_CURRENT_USER_PROFILE'
export const LISTEN_TO_SELECTED_USER_PROFILE = 'LISTEN_TO_SELECTED_USER_PROFILE'
export const LISTEN_TO_CURRENT_USER_PLAN = 'LISTEN_TO_CURRENT_USER_PLAN'

export const LISTEN_TO_HIGHLIGHT_COUNT = 'LISTEN_TO_HIGHLIGHT_COUNT'
export const LISTEN_TO_PREMIUM_INFO = 'LISTEN_TO_PREMIUM_INFO'

export const INCREMENT_HIGHLIGHT_COUNT = 'INCREMENT_HIGHLIGHT_COUNT'
export const DECREMENT_HIGHLIGHT_COUNT = 'DECREMENT_HIGHLIGHT_COUNT'